/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangTermsRouteImport } from './routes/$lang/terms'
import { Route as LangStudioRouteImport } from './routes/$lang/studio'
import { Route as LangSoonRouteImport } from './routes/$lang/soon'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangLegalRouteImport } from './routes/$lang/legal'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangBlogIndexRouteImport } from './routes/$lang/blog/index'
import { Route as LangUpdateStudioRouteImport } from './routes/$lang/update/studio'
import { Route as LangResourcesAssetRouteImport } from './routes/$lang/resources/asset'
import { Route as LangResourcesIdRouteImport } from './routes/$lang/resources/$id'
import { Route as LangPatchnoteSlugRouteImport } from './routes/$lang/patchnote/$slug'
import { Route as LangPacksYggdrasilRouteImport } from './routes/$lang/packs/yggdrasil'
import { Route as LangPacksNeoenchantRouteImport } from './routes/$lang/packs/neoenchant'
import { Route as LangBlogSlugRouteImport } from './routes/$lang/blog/$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRoute,
} as any)
const LangStudioRoute = LangStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => LangRoute,
} as any)
const LangSoonRoute = LangSoonRouteImport.update({
  id: '/soon',
  path: '/soon',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangLegalRoute = LangLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogIndexRoute = LangBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangRoute,
} as any)
const LangUpdateStudioRoute = LangUpdateStudioRouteImport.update({
  id: '/update/studio',
  path: '/update/studio',
  getParentRoute: () => LangRoute,
} as any)
const LangResourcesAssetRoute = LangResourcesAssetRouteImport.update({
  id: '/resources/asset',
  path: '/resources/asset',
  getParentRoute: () => LangRoute,
} as any)
const LangResourcesIdRoute = LangResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => LangRoute,
} as any)
const LangPatchnoteSlugRoute = LangPatchnoteSlugRouteImport.update({
  id: '/patchnote/$slug',
  path: '/patchnote/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangPacksYggdrasilRoute = LangPacksYggdrasilRouteImport.update({
  id: '/packs/yggdrasil',
  path: '/packs/yggdrasil',
  getParentRoute: () => LangRoute,
} as any)
const LangPacksNeoenchantRoute = LangPacksNeoenchantRouteImport.update({
  id: '/packs/neoenchant',
  path: '/packs/neoenchant',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/soon': typeof LangSoonRoute
  '/$lang/studio': typeof LangStudioRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/packs/neoenchant': typeof LangPacksNeoenchantRoute
  '/$lang/packs/yggdrasil': typeof LangPacksYggdrasilRoute
  '/$lang/patchnote/$slug': typeof LangPatchnoteSlugRoute
  '/$lang/resources/$id': typeof LangResourcesIdRoute
  '/$lang/resources/asset': typeof LangResourcesAssetRoute
  '/$lang/update/studio': typeof LangUpdateStudioRoute
  '/$lang/blog': typeof LangBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/soon': typeof LangSoonRoute
  '/$lang/studio': typeof LangStudioRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/packs/neoenchant': typeof LangPacksNeoenchantRoute
  '/$lang/packs/yggdrasil': typeof LangPacksYggdrasilRoute
  '/$lang/patchnote/$slug': typeof LangPatchnoteSlugRoute
  '/$lang/resources/$id': typeof LangResourcesIdRoute
  '/$lang/resources/asset': typeof LangResourcesAssetRoute
  '/$lang/update/studio': typeof LangUpdateStudioRoute
  '/$lang/blog': typeof LangBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/soon': typeof LangSoonRoute
  '/$lang/studio': typeof LangStudioRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/packs/neoenchant': typeof LangPacksNeoenchantRoute
  '/$lang/packs/yggdrasil': typeof LangPacksYggdrasilRoute
  '/$lang/patchnote/$slug': typeof LangPatchnoteSlugRoute
  '/$lang/resources/$id': typeof LangResourcesIdRoute
  '/$lang/resources/asset': typeof LangResourcesAssetRoute
  '/$lang/update/studio': typeof LangUpdateStudioRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/contact'
    | '/$lang/legal'
    | '/$lang/privacy'
    | '/$lang/soon'
    | '/$lang/studio'
    | '/$lang/terms'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/packs/neoenchant'
    | '/$lang/packs/yggdrasil'
    | '/$lang/patchnote/$slug'
    | '/$lang/resources/$id'
    | '/$lang/resources/asset'
    | '/$lang/update/studio'
    | '/$lang/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/contact'
    | '/$lang/legal'
    | '/$lang/privacy'
    | '/$lang/soon'
    | '/$lang/studio'
    | '/$lang/terms'
    | '/$lang'
    | '/$lang/blog/$slug'
    | '/$lang/packs/neoenchant'
    | '/$lang/packs/yggdrasil'
    | '/$lang/patchnote/$slug'
    | '/$lang/resources/$id'
    | '/$lang/resources/asset'
    | '/$lang/update/studio'
    | '/$lang/blog'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/contact'
    | '/$lang/legal'
    | '/$lang/privacy'
    | '/$lang/soon'
    | '/$lang/studio'
    | '/$lang/terms'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/packs/neoenchant'
    | '/$lang/packs/yggdrasil'
    | '/$lang/patchnote/$slug'
    | '/$lang/resources/$id'
    | '/$lang/resources/asset'
    | '/$lang/update/studio'
    | '/$lang/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/studio': {
      id: '/$lang/studio'
      path: '/studio'
      fullPath: '/$lang/studio'
      preLoaderRoute: typeof LangStudioRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/soon': {
      id: '/$lang/soon'
      path: '/soon'
      fullPath: '/$lang/soon'
      preLoaderRoute: typeof LangSoonRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal': {
      id: '/$lang/legal'
      path: '/legal'
      fullPath: '/$lang/legal'
      preLoaderRoute: typeof LangLegalRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/': {
      id: '/$lang/blog/'
      path: '/blog'
      fullPath: '/$lang/blog'
      preLoaderRoute: typeof LangBlogIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/update/studio': {
      id: '/$lang/update/studio'
      path: '/update/studio'
      fullPath: '/$lang/update/studio'
      preLoaderRoute: typeof LangUpdateStudioRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/resources/asset': {
      id: '/$lang/resources/asset'
      path: '/resources/asset'
      fullPath: '/$lang/resources/asset'
      preLoaderRoute: typeof LangResourcesAssetRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/resources/$id': {
      id: '/$lang/resources/$id'
      path: '/resources/$id'
      fullPath: '/$lang/resources/$id'
      preLoaderRoute: typeof LangResourcesIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/patchnote/$slug': {
      id: '/$lang/patchnote/$slug'
      path: '/patchnote/$slug'
      fullPath: '/$lang/patchnote/$slug'
      preLoaderRoute: typeof LangPatchnoteSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/packs/yggdrasil': {
      id: '/$lang/packs/yggdrasil'
      path: '/packs/yggdrasil'
      fullPath: '/$lang/packs/yggdrasil'
      preLoaderRoute: typeof LangPacksYggdrasilRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/packs/neoenchant': {
      id: '/$lang/packs/neoenchant'
      path: '/packs/neoenchant'
      fullPath: '/$lang/packs/neoenchant'
      preLoaderRoute: typeof LangPacksNeoenchantRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangContactRoute: typeof LangContactRoute
  LangLegalRoute: typeof LangLegalRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangSoonRoute: typeof LangSoonRoute
  LangStudioRoute: typeof LangStudioRoute
  LangTermsRoute: typeof LangTermsRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangPacksNeoenchantRoute: typeof LangPacksNeoenchantRoute
  LangPacksYggdrasilRoute: typeof LangPacksYggdrasilRoute
  LangPatchnoteSlugRoute: typeof LangPatchnoteSlugRoute
  LangResourcesIdRoute: typeof LangResourcesIdRoute
  LangResourcesAssetRoute: typeof LangResourcesAssetRoute
  LangUpdateStudioRoute: typeof LangUpdateStudioRoute
  LangBlogIndexRoute: typeof LangBlogIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangContactRoute: LangContactRoute,
  LangLegalRoute: LangLegalRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangSoonRoute: LangSoonRoute,
  LangStudioRoute: LangStudioRoute,
  LangTermsRoute: LangTermsRoute,
  LangIndexRoute: LangIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangPacksNeoenchantRoute: LangPacksNeoenchantRoute,
  LangPacksYggdrasilRoute: LangPacksYggdrasilRoute,
  LangPatchnoteSlugRoute: LangPatchnoteSlugRoute,
  LangResourcesIdRoute: LangResourcesIdRoute,
  LangResourcesAssetRoute: LangResourcesAssetRoute,
  LangUpdateStudioRoute: LangUpdateStudioRoute,
  LangBlogIndexRoute: LangBlogIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
