import type { ModMetadata } from "@/lib/minecraft/converter";
import { ModPlatforms } from "@/lib/minecraft/converter";

/**
 * Generates TOML content for Forge/NeoForge mods
 * @param commonData - Common mod metadata
 * @param platforms - Target platforms (affects loader generation)
 * @returns Formatted TOML content for mods.toml
 */
export function generateForgeMods(commonData: ModMetadata, platforms: ModPlatforms[]) {
    const modsToml = [
        `modLoader = '${platforms.includes(ModPlatforms.NEOFORGE) ? "javafml" : "lowcodefml"}'`,
        `loaderVersion = '[${platforms.includes(ModPlatforms.NEOFORGE) ? "1,)" : "40,)"}]'`,
        "license = 'LicenseRef-Datapack'",
        "showAsResourcePack = false",
        "mods = [",
        "  {",
        `    modId = '${commonData.id}',`,
        `    version = '${commonData.version}',`,
        `    displayName = '${commonData.name}',`,
        `    description = "${commonData.description.replace(/"/g, '\\"')}",`,
        `    logoFile = '${commonData.icon}',`,
        `    updateJSONURL = '${commonData.homepage}/updates.json',`,
        `    credits = 'Generated by Modrinth',`,
        `    authors = '${commonData.authors}',`,
        `    displayURL = '${commonData.homepage}'`,
        "  }",
        "]",
        `issueTrackerURL = '${commonData.issues}'`
    ].join("\n");

    return modsToml;
}
